# FeatherExperience plugin options
root:

  # The message pattern used for this plugin to display messages for players
  message_pattern: '[FExp] <message>'

  # Language
  language: en_us

  # Disable multi-language support?
  single_language: false

  # Features options
  features:
    # Bone meal options
    bone_meal:
      # Should we allow using bone meal on flowers?
      flower: true
      # Should we allow the usage of dispenser?
      flower_allow_dispenser: true

      # Enable renewable corals?
      coral: true
      # Should we allow the usage of dispenser?
      coral_allow_dispenser: true

      # Allow using bone meal on sugarcane?
      sugarcane: true
      # Should we allow the usage of dispenser?
      sugarcane_allow_dispenser: true

    # Deepslate options
    deepslate:
      # Enable deepslate farm?
      farm: true

    # Shulker box options
    shulkerbox:
      # Allow players open shulker box on their hand without placing it down?
      open: true

    # Bossbar options
    bossbar:
      # Show bossbar for Warden?
      warden: true

      # Show Warden's anger level on the bossbar?
      warden_show_anger: false

    # Save tridents from the void
    save_tridents_from_void:
      # Enable this feature?
      enabled: true

    # Turn mobs into spawn eggs when clicked with an egg
    mob_eggs:
      # Enable this feature?
      enabled: true

      # Disable this feature in these worlds.
      # !!! Please note that players can still use the spawn egg in these worlds !!!
      disabled_worlds:
        - disabled_world1
        - disabled_world2

      disabled_mobs:
        - minecraft:disabled_1
        - minecraft:disabled_2

  # Do not touch unless you know what you're doing!
  version: 4
