# FeatherExperience plugin options
root:

  # The message pattern used for this plugin to display messages for players
  message_pattern: '[FExp] <message>'

  # Language
  language: en_us

  # Disable multi-language support?
  single_language: false

  # Features options
  features:
    # Bone meal options
    bone_meal:
      # Should we allow using bone meal on flowers?
      flower: true
      # Should we allow the usage of dispenser?
      flower_allow_dispenser: true

      # Enable renewable corals?
      coral: true
      # Should we allow the usage of dispenser?
      coral_allow_dispenser: true

      # Allow using bone meal on sugarcane?
      sugarcane: true
      # Should we allow the usage of dispenser?
      sugarcane_allow_dispenser: true

    # Deepslate options
    deepslate:
      # Enable deepslate farm?
      farm: true

    # Shulker box options
    shulkerbox:
      # Allow players open shulker box on their hand without placing it down?
      open: true

      # A workaround for some plugins that sync players' inventories across multiple servers.
      # Wait for the configured ticks before we allow someone to open a box after they join
      #
      # PS: 1 second = 20 ticks
      wkar_open_delay: 40

    # Bossbar options
    bossbar:
      # Show bossbar for Warden?
      warden: true

      # Show Warden's anger level on the bossbar?
      warden_show_anger: false

    # Save tridents from the void
    save_tridents_from_void:
      # Enable this feature?
      enabled: true

    # Can items with Fire Aspect light candles?
    # Note that due to some limitations, players should left-click them rather than right-click like on Bedrock
    fire_aspect_lit_candles: true

    # Should players not have XP cooldown?
    no_exp_cooldown: true

    # Server links
    # The format is "<Type Preset>,<Custom Display Name>,<Link>"
    #
    # NOTE: The Link must be an HTTP or HTTPS link, or the entry won't appear on the client!
    #
    # The Type Preset can be one of the following elements:
    #  - NIL
    #  - BUG_REPORT
    #  - COMMUNITY_GUIDELINES
    #  - SUPPORT
    #  - STATUS
    #  - FEEDBACK
    #  - COMMUNITY
    #  - WEBSITE
    #  - FORUMS
    #  - NEWS
    #  - ANNOUNCEMENTS
    # When used, the client will display a localized string depending on their current language. Except "NIL"
    # Laving "NIL" will always make the plugin use Custom Display Name.
    # This isn't compatible with Custom Display Name.
    #
    # The Custom Display Name supports MiniMessage
    # If you wish to not have a custom display name for the link, leave it empty or "NIL" and the KnownType will be used.
    server_links:
      - "nil,minecraft.net,https://minecraft.net"
      - "NEWS,NIL,https://www.minecraft.net/en-us/articles"

    # Protocol options
    protocol:
      # Should we only include item components that have visual effects in vanilla?
      component_whitelist: true

    # Turn mobs into spawn eggs when clicked with an egg
    mob_eggs:
      # Enable this feature?
      enabled: true

      # Disable this feature in these worlds.
      # !!! Please note that players can still use the spawn egg in these worlds !!!
      #
      # Example:
      # disabled_worlds:
      #   - disabled_world1
      #   - disabled_world2
      disabled_worlds:
        - disabled_world1
        - disabled_world2

      # Disable this feature for certain mobs
      #
      # Example:
      # disabled_mobs:
      #   - minecraft:warden
      #   - minecraft:wither
      disabled_mobs:
        - minecraft:disabled_1
        - minecraft:disabled_2

      # Mob whitelist, only allow players to catch these mobs
      # Disabled when the list is empty
      #
      # Example:
      # mob_whitelist:
      #   - minecraft:villager
      #   - minecraft:allay
      mob_whitelist: []

    # Minecart speed settings
    # It will allow minecarts to run at different speed depend on which block it runs on
    minecart:
      # Enable this feature?
      enabled: true

      # Speed multipliers
      configs:
        - "minecraft:bedrock=1.5"

  # Do not touch unless you know what you're doing!
  version: 9
